/**
 * What the model code carries, and what it deliberately does not.
 *
 * The code represents what a user DEFINES: geometry, materials, sections, supports, loads,
 * cases and combinations, groups, and the project's stated settings. It does not represent
 * what the application PRODUCES — the detailing, the exports, the design's manual edits and
 * joint designs, the revision counters. Those are regenerated by designing again, and the
 * `.ded` remains the file that carries everything.
 *
 * Every top-level field of `ModelSnapshot` is in exactly one of the two lists below, with the
 * reason for a derived one written out. `coverage.test.ts` reads the snapshot's declared fields
 * from source and fails when a field is in neither: a field added to the model breaks the test
 * until someone decides which it is. That is what keeps "the code carries everything a user
 * defines" true as the model grows.
 */

/** Top-level snapshot fields the code carries, in the order it writes them. */
export const COVERED_FIELDS = [
  'name', 'analysisMode', 'localAxisConvention',
  'materials', 'sections', 'nodes', 'elements', 'plates', 'quads', 'supports',
  'loadCases', 'combinations', 'loads', 'constraints', 'connectors', 'groups', 'massSource', 'resultScopes', 'combinationRules', 'views', 'grid',
  'footings', 'geotechnical', 'footingMatPreferences', 'codeSettings', 'regulations',
] as const;

/** Top-level snapshot fields the code leaves out, and why. */
export const DERIVED_FIELDS: Readonly<Record<string, string>> = Object.freeze({
  provenance: 'Recorded by an importer about where the model came from; not something a user types.',
  nextId: 'Id counters, recomputed from the highest id in use when the code is read.',
  revisions: 'Revision counters the design pipeline advances; regenerated by designing.',
  detailing: 'The detailing document, produced by the design run from the model.',
  exports: 'Records of files the application exported.',
  manualEdits: 'Edits to produced reinforcement, meaningful only against the design they edit.',
  jointDesigns: 'Connection designs produced for the current node numbering.',
});

/**
 * Fields INSIDE a covered entity that are produced, not defined, and are left out of the code.
 *
 * A member's reinforcement is the design's output: auto-design writes it and the design run
 * regenerates it. Applying code to a model keeps each surviving member's reinforcement, so
 * editing geometry in the code does not throw the design away any more than editing it in the
 * viewport does.
 */
export const DERIVED_SUBFIELDS: Readonly<Record<string, readonly string[]>> = Object.freeze({
  elements: ['reinforcement'],
});
