/**
 * Every generator, in the order the Generators panel lists them, with a sample of what each
 * makes for its card.
 *
 * The panel opened on four buttons, Truss, Latticed column, Shed and Structures, the last a list
 * of eleven more, two of which (the lattice girder and the Howe roof truss) the first button
 * already built. Here every generator is one card, grouped by what it makes; the lattice girder
 * and the Howe roof truss are the lattice beam's webs and shapes and are not listed again. Their
 * kinds stay in `structures.ts`, so a group generated by them is still regenerated.
 *
 * Pure: no store, no i18n. The sample is the generator's own output for its default parameters.
 */
import { DEFAULT_TRUSS_PARAMS, generateTruss, type Topology } from '../engine/generators/truss-topology';
import { DEFAULT_LATTICE_COLUMN_PARAMS, generateLatticeColumn } from '../engine/generators/lattice-column';
import { DEFAULT_SHED_PARAMS, generateShed } from '../engine/generators/shed';
import { DEFAULT_STRUCTURE_PARAMS, generateStructure, type StructureKind } from '../engine/generators/structures';

export type GeneratorKind = 'truss' | 'column' | 'shed' | 'structure';

export interface GeneratorEntry {
  /** `truss`, `column`, `shed`, or a structure kind. */
  id: string;
  kind: GeneratorKind;
  structureKind?: StructureKind;
  /** i18n key of its name. */
  labelKey: string;
  /** Drawn as an elevation (plane structures) or in isometric (space ones). */
  view: 'elevation' | 'isometric';
}

export interface GeneratorCategory { id: string; labelKey: string; entries: GeneratorEntry[] }

const structure = (k: StructureKind, view: GeneratorEntry['view']): GeneratorEntry =>
  ({ id: k, kind: 'structure', structureKind: k, labelKey: `generator.structure.${k}`, view });

export const GENERATOR_CATALOG: readonly GeneratorCategory[] = [
  {
    id: 'beams', labelKey: 'generator.cat.beams', entries: [
      { id: 'truss', kind: 'truss', labelKey: 'generator.ui.kindTruss', view: 'elevation' },
      structure('continuousBeam', 'elevation'),
      structure('circularBeam', 'isometric'),
    ],
  },
  {
    id: 'columns', labelKey: 'generator.cat.columns', entries: [
      { id: 'column', kind: 'column', labelKey: 'generator.ui.kindColumn', view: 'elevation' },
    ],
  },
  {
    id: 'frames', labelKey: 'generator.cat.frames', entries: [
      structure('planeFrame', 'elevation'),
      structure('spaceFrame', 'isometric'),
      structure('floorGrid', 'isometric'),
    ],
  },
  {
    id: 'roofs', labelKey: 'generator.cat.roofs', entries: [
      { id: 'shed', kind: 'shed', labelKey: 'generator.ui.kindShed', view: 'isometric' },
      structure('sawtooth', 'elevation'),
      structure('cylindricalVault', 'isometric'),
      structure('dome', 'isometric'),
      structure('spaceTruss', 'isometric'),
    ],
  },
];

/** The structure kinds a listed generator covers whole, and so are not listed themselves. */
export const COVERED_STRUCTURE_KINDS: readonly StructureKind[] = ['latticeGirder', 'howeRoof'];

/** What the generator makes with its default parameters, for its card. */
export function sampleOf(e: GeneratorEntry): Topology | null {
  try {
    if (e.kind === 'truss') return generateTruss(DEFAULT_TRUSS_PARAMS);
    if (e.kind === 'column') return generateLatticeColumn(DEFAULT_LATTICE_COLUMN_PARAMS);
    if (e.kind === 'shed') return generateShed({ ...DEFAULT_SHED_PARAMS, frames: 4 });
    return generateStructure(e.structureKind!, DEFAULT_STRUCTURE_PARAMS[e.structureKind!]);
  } catch { return null; }
}
