/**
 * Objective 11 — what left the project, and what each file was entitled to say about itself.
 *
 * ── Why this designs a real building ──────────────────────────────
 *
 * Because the claim is that pressing a real export button records a real emission against a
 * real document revision. A seeded assembly has no document behind it, and `buildDocument`
 * refuses without coordinated detailing — which is the correct behaviour and makes the seeded
 * route unable to reach the thing under test.
 *
 * ── What is NOT here ──────────────────────────────────────────────
 *
 * The narrowing of the retouch set, the four states, and the failure path. Those are
 * `export-log.test.ts`'s and `rc-selection.test.ts`'s, where a document can be constructed with
 * a hand edit on a member it does not contain. What only the app can answer is that the button
 * writes the record, that the record survives the project moving on, and that the statement
 * reaches the document itself rather than only the panel.
 */

import { test, expect, designAll, loadModel, openDocumentsStage } from './fixtures';
import type { Page } from '@playwright/test';

test.use({ viewport: { width: 1400, height: 900 } });

/**
 * A designed, coordinated project sitting on the Documents stage.
 *
 * Detailing is generated by CLICKING the real command, and the stage is opened through
 * `openDocumentsStage` — the exports live in a collapsed stage like every other one, which is
 * `documents.spec.ts`'s own note and the reason a bare `toBeVisible` on the button waits
 * forever on a control that is attached.
 */
async function documents(page: Page) {
  await loadModel(page, 'rc-design-qa-8');
  await designAll(page);
  const d = page.getByTestId('detailing-disclosure');
  await expect(d).toBeVisible();
  await d.locator('> summary').click();
  const generate = page.getByTestId('cmd-generate-detailing');
  await expect(generate).toBeEnabled();
  await generate.click();
  await expect.poll(async () => page.evaluate(() =>
    (window.__stabileo as unknown as { detailingAssemblies(): unknown[] })
      .detailingAssemblies().length), { timeout: 30_000 }).toBeGreaterThan(0);
  await openDocumentsStage(page);
  await expect(page.getByTestId('doc-dxf')).toBeVisible({ timeout: 30_000 });
}

/** The emission records as PERSISTED, not as the panel renders them. */
function records(page: Page) {
  return page.evaluate(() =>
    (window.__stabileo as unknown as {
      exportRecords(): Array<{
        kind: string; revision: number; filename: string; state: string;
        retouched: { status: string; members: number[] };
      }>;
    }).exportRecords());
}

test.describe('@slow every export records itself', () => {
  /*
   * The defect. `exportRecordStore.record()` had no caller: the three handlers wrote a blob and
   * told nobody, so the list was empty in every project that has ever existed.
   */
  test('X1 — the list is empty until something is exported', async ({ pro: page }) => {
    await documents(page);
    expect(await records(page)).toEqual([]);
    await expect(page.getByTestId('export-log-empty')).toBeVisible();
  });

  test('X2 — exporting the drawings writes a record of that revision', async ({ pro: page }) => {
    await documents(page);
    await page.getByTestId('doc-dxf').click();

    await expect.poll(async () => (await records(page)).length).toBe(1);
    const [r] = await records(page);
    expect(r.kind).toBe('dxf');
    expect(r.state).toBe('ready');
    expect(r.filename).toContain('.dxf');
    expect(r.revision).toBeGreaterThan(0);
  });

  test('X3 — and the panel shows it, with the file name it offered', async ({ pro: page }) => {
    await documents(page);
    await page.getByTestId('doc-dxf').click();

    const row = page.getByTestId('export-record-0');
    await expect(row).toBeVisible();
    await expect(row).toHaveAttribute('data-kind', 'dxf');
    await expect(row).toContainText('.dxf');
  });

  /*
   * A real, empty claim. The project has a design and nothing in it was hand-edited, which is
   * different from a file that never recorded the information — and the panel words the two so
   * that no reader could mistake one for the other.
   */
  test('X4 — an untouched project says so, rather than saying nothing', async ({ pro: page }) => {
    await documents(page);
    await page.getByTestId('doc-dxf').click();

    const retouch = page.getByTestId('export-record-retouch-0');
    await expect(retouch).toHaveAttribute('data-retouch', 'known');
    await expect(retouch).toContainText('No member in this emission carried hand-edited');
  });
});

test.describe('@slow a record outlives the revision it came from', () => {
  /*
   * The question `rc-export-record.ts` opens with: "a user who exported the drawings, edited a
   * footing and came back to Documentos has no way to know the file in their folder no longer
   * corresponds." Stated as a comparison, never as a fault — exporting and then editing is a
   * normal working pattern.
   */
  test('X5 — it says so once the project has moved on', async ({ pro: page }) => {
    await documents(page);
    await page.getByTestId('doc-dxf').click();
    await expect(page.getByTestId('export-record-0')).toHaveAttribute('data-state', 'current');

    // Any change that retires the document moves the revision on. Pinning a bar is the
    // smallest one that does, and it is a real user gesture.
    const d = page.getByTestId('detailing-disclosure');
    if (await d.getAttribute('open') === null) await d.locator('> summary').click();
    await page.getByTestId('bar-list').locator('> summary').click();
    const lock = page.locator('[data-testid^="barlock-"]').first();
    test.skip(await lock.count() === 0, 'no bar to pin on this assembly');
    await lock.click();

    // Rebuilding the document is what advances the revision the record is compared against.
    await page.getByTestId('doc-report').click().catch(() => { /* the print window may block */ });
    await expect.poll(async () =>
      page.getByTestId('export-record-stale-1').isVisible().catch(() => false)
      || page.getByTestId('export-record-stale-0').isVisible().catch(() => false),
    { timeout: 20_000 }).toBe(true);
  });
});

test.describe('@slow the statement reaches the document, not only the panel', () => {
  /*
   * §4 asks every EXPORT to state its retouched members. A panel that said it while the DXF
   * did not would leave the sheet — the thing that gets printed and pinned up — silent.
   */
  test('X6 — the DXF note block carries the hand-edit sentence', async ({ pro: page }) => {
    await documents(page);
    const dxf = await page.evaluate(() =>
      (window.__stabileo as unknown as { detailingDxf(): string | null }).detailingDxf());
    expect(dxf).not.toBeNull();
    // The Spanish form: a drawing is a document, and `drawings.ts` states why it stays Spanish
    // even when the interface is not.
    expect(dxf).toContain('RETOCADOS A MANO');
  });
});
