/// Differential fuzzing — verify Rust solver matches TS solver fixtures.
///
/// Loads JSON fixtures generated by `web/src/lib/engine/__tests__/generate-fixtures.test.ts`,
/// runs Rust solver on the same input, and compares results field-by-field.
///
/// **Convention note**: The Rust solver stores element forces as member-end forces
/// (K·u + FEF), while the TS solver stores diagram-convention forces (K·u - FEF).
/// Displacements and reactions match exactly. For element forces, we compare via
/// `compute_diagram_value_at` which normalizes both conventions to the same values.
///
/// Run fixture generation first: cd web && npx vitest run generate-fixtures
/// Then: cd engine && cargo test --test differential_fuzz

mod helpers;

use dedaliano_engine::postprocess::combinations::*;
use dedaliano_engine::postprocess::diagrams::compute_diagram_value_at;
use dedaliano_engine::solver::linear::{solve_2d, solve_3d};
use dedaliano_engine::types::*;
use std::path::Path;

// ─── Comparison helpers ──────────────────────────────────────────

const REL_TOL_DISP: f64 = 1e-6;
const REL_TOL_FORCE: f64 = 1e-4;
const ABS_TOL: f64 = 1e-8;

fn close(actual: f64, expected: f64, rel_tol: f64) -> bool {
    let diff = (actual - expected).abs();
    if diff < ABS_TOL {
        return true;
    }
    let denom = expected.abs().max(1.0);
    diff / denom < rel_tol
}

fn assert_close(actual: f64, expected: f64, rel_tol: f64, label: &str) {
    assert!(
        close(actual, expected, rel_tol),
        "{}: actual={:.8e}, expected={:.8e}, diff={:.4e}",
        label,
        actual,
        expected,
        (actual - expected).abs()
    );
}

// ─── Fixture loading ─────────────────────────────────────────────

fn fixtures_dir() -> std::path::PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("tests")
        .join("fixtures")
}

fn load_fixture(name: &str) -> Option<String> {
    let path = fixtures_dir().join(format!("{}.json", name));
    if path.exists() {
        Some(std::fs::read_to_string(&path).unwrap_or_else(|e| {
            panic!("Failed to read fixture {}: {}", name, e)
        }))
    } else {
        None
    }
}

fn fixture_exists(name: &str) -> bool {
    fixtures_dir().join(format!("{}.json", name)).exists()
}

// ─── Displacement + reaction comparison ──────────────────────────

fn compare_displacements(prefix: &str, actual: &AnalysisResults, expected: &AnalysisResults) {
    let mut actual_disp: Vec<_> = actual.displacements.clone();
    let mut expected_disp: Vec<_> = expected.displacements.clone();
    actual_disp.sort_by_key(|d| d.node_id);
    expected_disp.sort_by_key(|d| d.node_id);

    assert_eq!(
        actual_disp.len(),
        expected_disp.len(),
        "{}: displacement count mismatch",
        prefix
    );
    for (a, e) in actual_disp.iter().zip(expected_disp.iter()) {
        assert_eq!(
            a.node_id, e.node_id,
            "{}: node_id mismatch in displacements",
            prefix
        );
        let lbl = format!("{} node{}", prefix, a.node_id);
        assert_close(a.ux, e.ux, REL_TOL_DISP, &format!("{} ux", lbl));
        assert_close(a.uy, e.uy, REL_TOL_DISP, &format!("{} uy", lbl));
        assert_close(a.rz, e.rz, REL_TOL_DISP, &format!("{} rz", lbl));
    }
}

fn compare_reactions(prefix: &str, actual: &AnalysisResults, expected: &AnalysisResults) {
    let mut actual_react: Vec<_> = actual.reactions.clone();
    let mut expected_react: Vec<_> = expected.reactions.clone();
    actual_react.sort_by_key(|r| r.node_id);
    expected_react.sort_by_key(|r| r.node_id);

    assert_eq!(
        actual_react.len(),
        expected_react.len(),
        "{}: reaction count mismatch",
        prefix
    );
    for (a, e) in actual_react.iter().zip(expected_react.iter()) {
        assert_eq!(
            a.node_id, e.node_id,
            "{}: node_id mismatch in reactions",
            prefix
        );
        let lbl = format!("{} react{}", prefix, a.node_id);
        assert_close(a.rx, e.rx, REL_TOL_FORCE, &format!("{} rx", lbl));
        assert_close(a.ry, e.ry, REL_TOL_FORCE, &format!("{} ry", lbl));
        assert_close(a.mz, e.mz, REL_TOL_FORCE, &format!("{} mz", lbl));
    }
}

// ─── Element force comparison via diagram evaluation ─────────────
// The Rust solver uses member-end force convention (K·u + FEF),
// while TS uses diagram convention (K·u - FEF).
// `compute_diagram_value_at` normalizes Rust forces to diagram convention.
// TS fixture values are already in diagram convention:
//   vStart = V(0), vEnd = V(1), mStart = M(0), mEnd = M(1)

fn compare_element_forces_via_diagrams(
    prefix: &str,
    actual: &AnalysisResults,
    expected: &AnalysisResults,
) {
    let mut actual_ef: Vec<_> = actual.element_forces.clone();
    let mut expected_ef: Vec<_> = expected.element_forces.clone();
    actual_ef.sort_by_key(|f| f.element_id);
    expected_ef.sort_by_key(|f| f.element_id);

    assert_eq!(
        actual_ef.len(),
        expected_ef.len(),
        "{}: element forces count mismatch",
        prefix
    );

    for (a, e) in actual_ef.iter().zip(expected_ef.iter()) {
        assert_eq!(
            a.element_id, e.element_id,
            "{}: element_id mismatch",
            prefix
        );
        let lbl = format!("{} elem{}", prefix, a.element_id);

        // Use compute_diagram_value_at on Rust output (member-end convention)
        // to get diagram-convention values. Compare against raw TS fixture
        // values which are already in diagram convention.
        let v0 = compute_diagram_value_at("shear", 0.0, a);
        let v1 = compute_diagram_value_at("shear", 1.0, a);
        let m0 = compute_diagram_value_at("moment", 0.0, a);
        let m1 = compute_diagram_value_at("moment", 1.0, a);
        let n0 = compute_diagram_value_at("axial", 0.0, a);
        let n1 = compute_diagram_value_at("axial", 1.0, a);

        assert_close(n0, e.n_start, REL_TOL_FORCE, &format!("{} N(0)", lbl));
        assert_close(n1, e.n_end, REL_TOL_FORCE, &format!("{} N(1)", lbl));
        assert_close(v0, e.v_start, REL_TOL_FORCE, &format!("{} V(0)", lbl));
        assert_close(v1, e.v_end, REL_TOL_FORCE, &format!("{} V(1)", lbl));
        assert_close(m0, e.m_start, REL_TOL_FORCE, &format!("{} M(0)", lbl));
        assert_close(m1, e.m_end, REL_TOL_FORCE, &format!("{} M(1)", lbl));

        // Also compare midspan diagram values to catch interpolation differences
        let v_mid = compute_diagram_value_at("shear", 0.5, a);
        let m_mid = compute_diagram_value_at("moment", 0.5, a);
        // Compute expected midspan from TS using its linear/parabolic interpolation:
        // For shear (linear with UDL): V(0.5) = (vStart + vEnd) / 2  for uniform load
        // For moment (parabolic with UDL): interpolation is more complex
        // We just check that midspan is within the range of endpoints (sanity check)
        let v_range = (e.v_start.min(e.v_end), e.v_start.max(e.v_end));
        let m_range = (e.m_start.min(e.m_end), e.m_start.max(e.m_end));
        // For elements with distributed loads, moment can exceed endpoint range
        // Just verify midspan is finite
        assert!(v_mid.is_finite(), "{} V(0.5) not finite", lbl);
        assert!(m_mid.is_finite(), "{} M(0.5) not finite", lbl);
        let _ = (v_range, m_range); // suppress unused warning
    }
}

// ─── Direct element force comparison (for combo results in same convention) ──

fn compare_element_forces_direct(
    prefix: &str,
    actual: &AnalysisResults,
    expected: &AnalysisResults,
) {
    let mut actual_ef: Vec<_> = actual.element_forces.clone();
    let mut expected_ef: Vec<_> = expected.element_forces.clone();
    actual_ef.sort_by_key(|f| f.element_id);
    expected_ef.sort_by_key(|f| f.element_id);

    assert_eq!(
        actual_ef.len(),
        expected_ef.len(),
        "{}: element forces count mismatch",
        prefix
    );
    for (a, e) in actual_ef.iter().zip(expected_ef.iter()) {
        let lbl = format!("{} elem{}", prefix, a.element_id);
        assert_close(a.n_start, e.n_start, REL_TOL_FORCE, &format!("{} nStart", lbl));
        assert_close(a.n_end, e.n_end, REL_TOL_FORCE, &format!("{} nEnd", lbl));
        assert_close(a.v_start, e.v_start, REL_TOL_FORCE, &format!("{} vStart", lbl));
        assert_close(a.v_end, e.v_end, REL_TOL_FORCE, &format!("{} vEnd", lbl));
        assert_close(a.m_start, e.m_start, REL_TOL_FORCE, &format!("{} mStart", lbl));
        assert_close(a.m_end, e.m_end, REL_TOL_FORCE, &format!("{} mEnd", lbl));
    }
}

// ─── 3D comparison (displacements + reactions only) ──────────────
// 3D element force conventions differ between TS and Rust (local axis mapping),
// but displacements and reactions in global coordinates match exactly.

fn compare_results_3d(prefix: &str, actual: &AnalysisResults3D, expected: &AnalysisResults3D) {
    let mut actual_disp: Vec<_> = actual.displacements.clone();
    let mut expected_disp: Vec<_> = expected.displacements.clone();
    actual_disp.sort_by_key(|d| d.node_id);
    expected_disp.sort_by_key(|d| d.node_id);

    assert_eq!(
        actual_disp.len(),
        expected_disp.len(),
        "{}: 3D displacement count mismatch",
        prefix
    );
    for (a, e) in actual_disp.iter().zip(expected_disp.iter()) {
        let lbl = format!("{} node{}", prefix, a.node_id);
        assert_close(a.ux, e.ux, REL_TOL_DISP, &format!("{} ux", lbl));
        assert_close(a.uy, e.uy, REL_TOL_DISP, &format!("{} uy", lbl));
        assert_close(a.uz, e.uz, REL_TOL_DISP, &format!("{} uz", lbl));
        assert_close(a.rx, e.rx, REL_TOL_DISP, &format!("{} rx", lbl));
        assert_close(a.ry, e.ry, REL_TOL_DISP, &format!("{} ry", lbl));
        assert_close(a.rz, e.rz, REL_TOL_DISP, &format!("{} rz", lbl));
    }

    let mut actual_react: Vec<_> = actual.reactions.clone();
    let mut expected_react: Vec<_> = expected.reactions.clone();
    actual_react.sort_by_key(|r| r.node_id);
    expected_react.sort_by_key(|r| r.node_id);

    assert_eq!(
        actual_react.len(),
        expected_react.len(),
        "{}: 3D reaction count mismatch",
        prefix
    );
    for (a, e) in actual_react.iter().zip(expected_react.iter()) {
        let lbl = format!("{} react{}", prefix, a.node_id);
        assert_close(a.fx, e.fx, REL_TOL_FORCE, &format!("{} fx", lbl));
        assert_close(a.fy, e.fy, REL_TOL_FORCE, &format!("{} fy", lbl));
        assert_close(a.fz, e.fz, REL_TOL_FORCE, &format!("{} fz", lbl));
        assert_close(a.mx, e.mx, REL_TOL_FORCE, &format!("{} mx", lbl));
        assert_close(a.my, e.my, REL_TOL_FORCE, &format!("{} my", lbl));
        assert_close(a.mz, e.mz, REL_TOL_FORCE, &format!("{} mz", lbl));
    }

    // Element force count check (structural sanity)
    assert_eq!(
        actual.element_forces.len(),
        expected.element_forces.len(),
        "{}: 3D element forces count mismatch",
        prefix
    );
}

// ─── Canonical 2D solve parity ───────────────────────────────────

fn run_2d_parity(name: &str) {
    let input_json = load_fixture(&format!("{}-input", name))
        .unwrap_or_else(|| {
            panic!(
                "Missing fixture {}-input.json — run fixture generator first",
                name
            )
        });
    let expected_json = load_fixture(&format!("{}-results", name))
        .unwrap_or_else(|| panic!("Missing fixture {}-results.json", name));

    let input: SolverInput = serde_json::from_str(&input_json)
        .unwrap_or_else(|e| panic!("Failed to parse {}-input.json: {}", name, e));
    let expected: AnalysisResults = serde_json::from_str(&expected_json)
        .unwrap_or_else(|e| panic!("Failed to parse {}-results.json: {}", name, e));

    let actual =
        solve_2d(&input).unwrap_or_else(|e| panic!("Rust solver failed on {}: {}", name, e));

    compare_displacements(name, &actual, &expected);
    compare_reactions(name, &actual, &expected);
    compare_element_forces_via_diagrams(name, &actual, &expected);
}

#[test]
fn test_fuzz_ss_beam() {
    run_2d_parity("ss-beam");
}

#[test]
fn test_fuzz_cantilever() {
    run_2d_parity("cantilever");
}

#[test]
fn test_fuzz_portal_d() {
    run_2d_parity("portal-d");
}

#[test]
fn test_fuzz_portal_l() {
    run_2d_parity("portal-l");
}

#[test]
fn test_fuzz_portal_w() {
    run_2d_parity("portal-w");
}

// ─── 3D canonical test ───────────────────────────────────────────

#[test]
fn test_fuzz_cantilever_3d() {
    let input_json = load_fixture("cantilever-3d-input")
        .expect("Missing cantilever-3d-input.json — run fixture generator first");
    let expected_json =
        load_fixture("cantilever-3d-results").expect("Missing cantilever-3d-results.json");

    let input: SolverInput3D =
        serde_json::from_str(&input_json).expect("Failed to parse cantilever-3d-input.json");
    let expected: AnalysisResults3D =
        serde_json::from_str(&expected_json).expect("Failed to parse cantilever-3d-results.json");

    let actual = solve_3d(&input).expect("Rust 3D solver failed");

    compare_results_3d("cantilever-3d", &actual, &expected);
}

// ─── Combination parity ─────────────────────────────────────────
// Combo tests use TS fixture results as input to Rust combine_results.
// Both TS and Rust combine_results do simple linear algebra, so
// the output shares the same convention → direct comparison works.

fn run_combo_parity(name: &str, case_names: &[(&str, usize)]) {
    let combo_json =
        load_fixture(name).unwrap_or_else(|| panic!("Missing fixture {}.json", name));

    let combo_data: serde_json::Value = serde_json::from_str(&combo_json)
        .unwrap_or_else(|e| panic!("Failed to parse {}.json: {}", name, e));

    let expected: AnalysisResults = serde_json::from_value(combo_data["results"].clone())
        .unwrap_or_else(|e| panic!("Failed to parse results from {}.json: {}", name, e));

    let factors_val = combo_data["factors"].as_array().unwrap();
    let mut factors = Vec::new();
    let mut cases = Vec::new();

    for f in factors_val {
        let case_id = f["caseId"].as_u64().unwrap() as usize;
        let factor = f["factor"].as_f64().unwrap();
        factors.push(CombinationFactor { case_id, factor });

        let case_name = case_names
            .iter()
            .find(|(_, id)| *id == case_id)
            .unwrap_or_else(|| panic!("No case fixture for caseId {} in {}", case_id, name))
            .0;
        let case_results_json = load_fixture(&format!("{}-results", case_name))
            .unwrap_or_else(|| panic!("Missing {}-results.json for combo {}", case_name, name));
        let case_results: AnalysisResults = serde_json::from_str(&case_results_json).unwrap();
        cases.push(CaseEntry {
            case_id,
            results: case_results,
        });
    }

    let actual = combine_results(&CombinationInput { factors, cases })
        .unwrap_or_else(|| panic!("Rust combine_results returned None for {}", name));

    compare_displacements(&format!("combo:{}", name), &actual, &expected);
    compare_reactions(&format!("combo:{}", name), &actual, &expected);
    compare_element_forces_direct(&format!("combo:{}", name), &actual, &expected);
}

#[test]
fn test_fuzz_portal_combo_12d_16l() {
    run_combo_parity(
        "portal-combo-12d-16l",
        &[("portal-d", 1), ("portal-l", 2), ("portal-w", 3)],
    );
}

#[test]
fn test_fuzz_portal_combo_12d_l_16w() {
    run_combo_parity(
        "portal-combo-12d-l-16w",
        &[("portal-d", 1), ("portal-l", 2), ("portal-w", 3)],
    );
}

#[test]
fn test_fuzz_portal_combo_09d_16w() {
    run_combo_parity(
        "portal-combo-09d-16w",
        &[("portal-d", 1), ("portal-l", 2), ("portal-w", 3)],
    );
}

// ─── Envelope parity ─────────────────────────────────────────────
// Solve each case with Rust, combine, compute envelope, compare against TS fixture.

#[test]
fn test_fuzz_portal_envelope() {
    let envelope_json = load_fixture("portal-envelope")
        .expect("Missing portal-envelope.json — run fixture generator first");
    let expected: FullEnvelope =
        serde_json::from_str(&envelope_json).expect("Failed to parse portal-envelope.json");

    // Solve each case with Rust solver (member-end convention)
    let case_inputs: Vec<(&str, usize)> = vec![("portal-d", 1), ("portal-l", 2), ("portal-w", 3)];
    let mut rust_case_results: std::collections::HashMap<usize, AnalysisResults> =
        std::collections::HashMap::new();
    for &(case_name, case_id) in &case_inputs {
        let json = load_fixture(&format!("{}-input", case_name)).unwrap();
        let input: SolverInput = serde_json::from_str(&json).unwrap();
        let result = solve_2d(&input).unwrap();
        rust_case_results.insert(case_id, result);
    }

    // Build combos using Rust solver results
    let combos_spec: Vec<Vec<(usize, f64)>> = vec![
        vec![(1, 1.2), (2, 1.6)],
        vec![(1, 1.2), (2, 1.0), (3, 1.6)],
        vec![(1, 0.9), (3, 1.6)],
    ];

    let mut combo_results = Vec::new();
    for factors_spec in &combos_spec {
        let factors: Vec<CombinationFactor> = factors_spec
            .iter()
            .map(|&(case_id, factor)| CombinationFactor { case_id, factor })
            .collect();
        let cases: Vec<CaseEntry> = factors_spec
            .iter()
            .map(|&(case_id, _)| CaseEntry {
                case_id,
                results: rust_case_results[&case_id].clone(),
            })
            .collect();
        combo_results.push(combine_results(&CombinationInput { factors, cases }).unwrap());
    }

    let actual = compute_envelope(&combo_results).expect("Rust compute_envelope returned None");

    // Compare globalMax for each diagram kind
    assert_close(
        actual.moment.global_max,
        expected.moment.global_max,
        REL_TOL_FORCE,
        "envelope moment globalMax",
    );
    assert_close(
        actual.shear.global_max,
        expected.shear.global_max,
        REL_TOL_FORCE,
        "envelope shear globalMax",
    );
    assert_close(
        actual.axial.global_max,
        expected.axial.global_max,
        REL_TOL_FORCE,
        "envelope axial globalMax",
    );

    // Compare maxAbsResults: displacements and reactions
    compare_displacements(
        "envelope:maxAbs",
        &actual.max_abs_results,
        &expected.max_abs_results,
    );
    compare_reactions(
        "envelope:maxAbs",
        &actual.max_abs_results,
        &expected.max_abs_results,
    );

    // Compare per-element envelope diagram data
    for kind_name in &["moment", "shear", "axial"] {
        let (actual_diag, expected_diag) = match *kind_name {
            "moment" => (&actual.moment, &expected.moment),
            "shear" => (&actual.shear, &expected.shear),
            "axial" => (&actual.axial, &expected.axial),
            _ => unreachable!(),
        };

        assert_eq!(
            actual_diag.elements.len(),
            expected_diag.elements.len(),
            "Envelope {} element count mismatch",
            kind_name
        );

        let mut actual_elems = actual_diag.elements.clone();
        let mut expected_elems = expected_diag.elements.clone();
        actual_elems.sort_by_key(|e| e.element_id);
        expected_elems.sort_by_key(|e| e.element_id);

        for (ae, ee) in actual_elems.iter().zip(expected_elems.iter()) {
            assert_eq!(ae.element_id, ee.element_id);
            for (j, ((ap, an), (ep, en))) in ae
                .pos_values
                .iter()
                .zip(ae.neg_values.iter())
                .zip(ee.pos_values.iter().zip(ee.neg_values.iter()))
                .enumerate()
            {
                let lbl = format!(
                    "envelope {} elem{} pt{}",
                    kind_name, ae.element_id, j
                );
                assert_close(*ap, *ep, REL_TOL_FORCE, &format!("{} pos", lbl));
                assert_close(*an, *en, REL_TOL_FORCE, &format!("{} neg", lbl));
            }
        }
    }
}

// ─── Random model parity ─────────────────────────────────────────

macro_rules! random_parity_test {
    ($name:ident, $seed:expr) => {
        #[test]
        fn $name() {
            let seed = $seed;
            let skip_name = format!("random-{}-skip", seed);
            if fixture_exists(&skip_name) {
                return;
            }
            let input_name = format!("random-{}-input", seed);
            if !fixture_exists(&input_name) {
                eprintln!("Skipping random-{}: fixture not found", seed);
                return;
            }
            run_2d_parity(&format!("random-{}", seed));
        }
    };
}

random_parity_test!(test_fuzz_random_1, 1);
random_parity_test!(test_fuzz_random_2, 2);
random_parity_test!(test_fuzz_random_3, 3);
random_parity_test!(test_fuzz_random_4, 4);
random_parity_test!(test_fuzz_random_5, 5);
random_parity_test!(test_fuzz_random_6, 6);
random_parity_test!(test_fuzz_random_7, 7);
random_parity_test!(test_fuzz_random_8, 8);
random_parity_test!(test_fuzz_random_9, 9);
random_parity_test!(test_fuzz_random_10, 10);
random_parity_test!(test_fuzz_random_11, 11);
random_parity_test!(test_fuzz_random_12, 12);
random_parity_test!(test_fuzz_random_13, 13);
random_parity_test!(test_fuzz_random_14, 14);
random_parity_test!(test_fuzz_random_15, 15);
random_parity_test!(test_fuzz_random_16, 16);
random_parity_test!(test_fuzz_random_17, 17);
random_parity_test!(test_fuzz_random_18, 18);
random_parity_test!(test_fuzz_random_19, 19);
random_parity_test!(test_fuzz_random_20, 20);
